[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_GRAPHQL_URL = "https://learn.reboot01.com/api/graphql-engine/v1/graphql"
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
